name: Update translations from source

on:
  push:
    paths: '**.py'

jobs:
  build_translations:
    name: Update Translations
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build translation files
        run: |
          [[ -x /usr/bin/pylupdate5 ]] || apt install pyqt5-dev-tools
          for srcfile in sway_input_config/langs/*.ts; do
            lang=$(echo $(basename $srcfile) | sed -E "s/lang_(.*).ts/\1/g")
            echo "Updating translation file for $lang"
            ./locale-gen.sh $lang
            git add $srcfile
          done
          git diff --cached --exit-code > /dev/null && (echo "No translation changes detected") || (
            git config user.name github-actions &&
            git config user.email github-actions@github.com &&
            git commit -m "Automatic Translation Source updates" &&
            git push
          )
